apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  source:
    repoURL: git@github.com:pascariucosmin93/todolist-giops.git
    targetRevision: main
    path: apps/todolist
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
