apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.4
          args:
            - start-dev
            - --import-realm
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: dev-file
          envFrom:
            - secretRef:
                name: keycloak-secret
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-config

